### ISSUE TITLE
Support VS 2019

### ISSUE THREAD

**Issue by twenzel** [ppumkin/PrestoCoverage#17]
Please add support for Visual Studio 2019.

**Comment by ppumkin** [comment]
It should work to be honest. Did you try?

**Comment by ppumkin** [comment]
unless the installer is locked to vs2017.. otherwise its just a config thing in the installer

**Comment by twenzel** [comment]
That's the problem, the installer is locked to VS2017 and the Extension gallery within VS2019 does not list your extension.

**Comment by ppumkin** [comment]
I have uploaded 1.16.3 to extension store. I have a PR but not sure why I have so many changes I cant remember now if those are working changes or not.. please let me know if all seems OK after update

**Comment by ppumkin** [comment]
Please use 1.16.4 as there was some dependency that I did not need and is not installed in VS2019 anyway.

**Comment by bobted** [comment]
I have 1.16.4 installed in 2019 Pro, but get the below error when running MSTest unit tests.

```
System.TypeAccessException: Attempt by method 'PrestoCoverage.PrestoCoverageCore.OnTestExecutionStarting(System.Object, Microsoft.VisualStudio.TestWindow.Extensibility.OperationStateChangedEventArgs)' to access type 'Microsoft.VisualStudio.TestWindow.Controller.TestRunConfiguration' failed.
   at PrestoCoverage.PrestoCoverageCore.OnTestExecutionStarting(Object sender, OperationStateChangedEventArgs stateArgs) in C:\Projects\PrestoCoverage\PrestoCoverage\PrestoCoverage\PrestoCoverageCore.cs:line 66
   at PrestoCoverage.PrestoCoverageContainerDiscoverer.OperationState_StateChanged(Object sender, OperationStateChangedEventArgs e) in C:\Projects\PrestoCoverage\PrestoCoverage\PrestoCoverage\PrestoCoverageContainerDiscoverer.cs:line 73
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.TestWindow.Controller.OperationData.OnStateChanged(OperationStateChangedEventArgs e)
   at Microsoft.VisualStudio.TestWindow.Controller.OperationData.Microsoft.VisualStudio.TestWindow.Controller.IOperationData.OnRequestStateChanged(Object sender, RequestStateChangedEventArgs e)
   at Microsoft.VisualStudio.TestWindow.Controller.Request.SetState(RequestStates newState
```
Hopefully this helps.

**Comment by ppumkin** [comment]
I am looking into this. I noticed this after installing but didnt get round to it yet.

**Comment by replaysMike** [comment]
I too get this exact issue.

**Comment by replaysMike** [comment]
I should note for others as well, you actually need to uninstall the extension to be able to run tests again as disabling it didn't affect the error.

**Comment by ppumkin** [comment]
Sorry guys... Something has changed in VS2019 and I am not sure when I will have time to sort it out.

**Comment by ppumkin** [comment]
Well I found the problem.. They changed the TestWindows dll in VS2019 so when you try and run a test I try to use reflection to get some information about what is going on with the tests.

Why they did is beyond me but I am to stupid to work out how to get this information the "Extensions way" 

The thing I was using in VS2017, the DLL I had to manually reference had a **public sealed** class and the 2019 version is **internal sealed** which prevents me from casting to this type. I can probably go deeper into reflection and get this... but for the love of god.. why?!

```
#region Assembly Microsoft.VisualStudio.TestWindow.Core, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestWindow.Core.dll
#endregion

namespace Microsoft.VisualStudio.TestWindow.Controller
{
    **public** sealed class TestRunConfiguration : RequestConfiguration, ITestRunRequestConfiguration, TestPlatform.ObjectModel.Client.ITestRunConfiguration, Controller.ITestRunConfigurationProvider
    {
```


```
#region Assembly Microsoft.VisualStudio.TestWindow.Core, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestWindow.Core.dll
#endregion

namespace Microsoft.VisualStudio.TestWindow.Controller
{
    **internal** sealed class TestRunConfiguration :
```

**Comment by ppumkin** [comment]
Well digging in a bit deeper everything got changed to internal. 

If I was conspiracy theorists I would say that one of the Microsoft guys from the Coverlet git saw this and the only reason to close this up to keep this kind of feature for Enterprise users only. But I have no proof of that, I am tired and pissed about this. So sorry guys

No VS2019 support!

**Comment by replaysMike** [comment]
Ah man don’t you hate when they do stuff like this? I wonder if it was to prevent not having Enterprise to get these stats. I wonder how they do it in DotCover?

**Comment by ppumkin** [comment]
Well if I play the conspiracy card I have to be fair and play the good guy theory card too.

I believe VS2019 is going to force all extensions to run async and they are probably locking down sync access like this down. The thing is the plugin and coverlet run under the VS Thread, luckily its not a massive issue because it doesn't slow down usage while writing code.. and when we run tests we usually go make a brew so nobody notices a minor speed slowdown.

So really.. I have to redo everything to be async and it would be nice if dependency injection worked from VS into extensions (which it doesnt) And all the shit I have seen is still COM hooks, weird export attributes and then my attempt with meta programming.

I have actually stared at the DotCover (and others) source code for hours. I can hardly make head and tails of it but I have literally nicked their VisualStudioExtensions file to help with a few things.

But I just cannot work out how they hook into the Test Window. Usually when I struggle with these things its because I am doing it wrong. But I cannot find any good useful information about Extension developing (like not the shitty examples that avoid using anything useful from VS) 😢 

So why do I need the test window? 
A private object "Configuration" contains the following information about the test runner.

1. Is the debugger attached? 
   1.  If yes then do not attach Coverlet because coverlet modifes part of the binary and causes debugging to fail
1. Which Test projects are being run?
   1.  and iterate over them to give me the exact path of the DLL so I can tell Coverlet what to use

**Comment by ppumkin** [comment]
> I wonder how they do it in DotCover?

I replied before I was staring at the DotCover source code... there is no source code.. I got confused with another open source project AxoCover I think.  

The way DotCover does it is by running its own TestRunner out of process. They gather the data then from their own internal gubbins.

**Comment by dozer75** [comment]
Sad thing it didn't work in 2019 since it looks to be a simple and handy extension, but could you remove 2019 from supported versions on the marketplace until this is solved? So people doesn't get confused?

**Comment by guillaume86** [comment]
Do you need TestWindow.dll for the basic watch coverage.json files and color gutters functionality?
I don't mind running `dotnet watch` with the appropriate settings myself.

**Comment by ppumkin** [comment]
Ahh yes. I completely forgot about that aspect I am so frustrated with this automatic thing.
Will try and sort that asap to get it working with 2019 in a limited state at least, until I find some other way to fix the testwindow thing

**Comment by iainnicol** [comment]
@ppumkin, you say

> So why do I need the test window?
> A private object "Configuration" contains the following information about the test runner.

Given the trouble we've had with reflection, I have been thinking a bit about possible alternative approaches.

> 1. Is the debugger attached?
>   i. If yes then do not attach Coverlet because coverlet modifes part of the binary and causes debugging to fail

I eventually realised the question to ask is: *How does coverlet itself handle this?* Coverlet has a package for direct VSTest DLL integration. Another package is offered for MSBuild integration, but that doesn't help us because the VS test runner uses... VSTest directly.

Now, the coverlet VSTest integration is essentially a ``DataCollector``. The coverlet docs suggest running this collector from the ``dotnet test`` command line. But collectors can [also be used](https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md#using-datacollector) from ``.runsettings`` files, including [from Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#specify-a-run-settings-file-in-the-ide).

So IMHO we don't really need any code here. Instead we just need documentation, mainly an example ``.runsettings`` file.

> 2. Which Test projects are being run?

And hopefully the answer here is similar: we need a ``DataCollector``, though this time we right our own, write our own, to simply add to our list of recently run test projects. This might require some IPC between the data collector and the main PrestoCoverage instance.

What do you think? Is this worth me or you prototyping?

**Comment by ppumkin** [comment]
I know what I am trying to do is probably incorrect. I have learnt about this years ago in development. If it seems too difficult it’s probably because it’s the wrong way 😂

I am a newb to extensions and what you have proposed is a different way. Probably the correct way. So yes please try and make a branch if you will. 

All we need to know is to attach coverlet before the test runs... ? And when they finish to aggregate the results.

**Comment by ppumkin** [comment]
https://github.com/Microsoft/vstest/tree/master/test/TestAssets/OutOfProcDataCollector

This looks promising. I am sure I have come across before... not sure why I decided to go down reflection route. Probably couldn’t get enough information out of that data collector.

**Comment by iainnicol** [comment]
Ah. Well hopefully I have better luck then!

I am amused by your comments about difficult things being the wrong way. Yes. But sometimes wrong code is the only way!

**Comment by ppumkin** [comment]
Please try it. I hope you can find a solution.

**Comment by iainnicol** [comment]
Good news. This approach works. The code needs tidied up, but I hope to contribute it next week.

Turns out this is bleeding edge stuff. The coverlet DataCollector was only released a week ago, the day I started looking at this! It just wasn't available when you took a look at data collectors.

**Comment by ppumkin** [comment]
Ahhh right. Very interesting. I have a feeling your findings will make it a lot easier understand now. But is this stuff is compatible with VS2017 ? Or that can still stay with the fugly reflection garbage?

**Comment by LoriBru** [comment]
Ehi guys! Any update on the VS2019 compatibility?

**Comment by Hviid** [comment]
@iainnicol Any news on this issue?

**Comment by iainnicol** [comment]
Ah, sorry, mainly I got distracted by other things. I will work on this this weekend.

I had a minor but required pull request rejected for Presto itself, which is unfortunate. I may need a hack. Worst case, I suppose, isn't that bad because Presto has already been forked.

**Comment by ppumkin** [comment]
You mean a PR for coverlet right ? Did they for coverlet too?

________________________________

**Comment by iainnicol** [comment]
Oops. I indeed meant coverlet.

We need coverlet to target netstandard (tonerdo/coverlet#470) so that the coverlet VS Test collector works within Visual Studio.  Otherwise their VS Test collector only works from the console.

So what to to? Hopefully VS has changed and now works with netcoreapp. If not, maybe we can still consume the coverlet nuget package, but hack the metadata to look like netstandard. Else we have to fork. I know you've had to fork coverlet before, but I don't want to add a second reason for the fork!

**Comment by ppumkin** [comment]
What if we fix what we need in our fork. There is nothing changed there really so we could upgrade the pull, upgrade it to net standard ? And PR it back maybe ?

________________________________

**Comment by cmenzi** [comment]
Any updates on this?

**Comment by ppumkin** [comment]
Not yet sorry. Will have a look next week I hope. Somebody had an idea but not sure if it worked. There are no guides to any of this 🧐😕

________________________________

**Comment by ppumkin** [comment]
> Good news. This approach works. The code needs tidied up, but I hope to contribute it next week.
> 
> Turns out this is bleeding edge stuff. The coverlet DataCollector was only released a week ago, the day I started looking at this! It just wasn't available when you took a look at data collectors.

@iainnicol I have a fork running here https://github.com/ppumkin/coverlet we can change whatever we need to get this going. I am also building the Experimental Coverlet package using that fork, which on on the VS Store.

Problem is that coverlet do not want to "open" the coverlet.core because they afraid to change API's that may cause backlash from the community... but also they not offering any solutions so i just forked it and told them im going to build the core one on my own responsibility. They said OK. 

So if you got a coverlet PR, do it against my fork, i will rebuild the package that this project uses and lets get VS2019 working... ??! 😄

**Comment by ppumkin** [comment]
I released 1.16.5 that will not cause that dumb ass exception to show any more.. 

**but the automagic coverage DOES NOT WORK IN YET**

You can only use the watch folder function in VS2019 for NOW..  atleast something for the time being.

Sorry for taking so long to get to it.

**Comment by jotatoledo** [comment]
Just found out your extension after almost giving up hope on coverage-tools for VS.

> Sorry for taking so long to get to it.

Thanks for the amazing work. This is OSS, so dont feel sorry for progress to take its time!

**Comment by adrianhara** [comment]
I'm using VS2019 Professional and get no gutters. The json report is generated under `c:\coverlet\xunittestcoverage.json `, looks good, the extension is installed, but no gutters. Any idea what I could try?

**Comment by eternaldensity** [comment]
Installed Presto in VS2019 Community and got the following error log when I ran tests from text explorer:
```
[19/09/2019 2:40:59.975 PM Error] System.MissingMethodException: Method not found: 'Boolean Microsoft.VisualStudio.TestWindow.Controller.TestRunConfiguration.get_Debug()'.
   at PrestoCoverage.PrestoCoverageCore.OnTestExecutionStarting(Object sender, OperationStateChangedEventArgs stateArgs)
   at PrestoCoverage.PrestoCoverageContainerDiscoverer.OperationState_StateChanged(Object sender, OperationStateChangedEventArgs e) in C:\Projects\PrestoCoverage\PrestoCoverage\PrestoCoverage\PrestoCoverageContainerDiscoverer.cs:line 73
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.TestWindow.Controller.OperationData.<>c__DisplayClass43_0.<OnStateChanged>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

So it doesn't even generate the report :(

**Comment by brianhill-bfs** [comment]
I have the same issue as @adrianhara with VS2019 Professional. I have coverage output, but nothing loaded in VS.

**Comment by siuarima9** [comment]
I'm using vs2019 but this extension isn't working..

**Comment by eduardocp** [comment]
@ppumkin 

I think this resolve the problem of internal classes/methods:
```c#
dynamic testRequestConfiguration = stateArgs.Operation.GetType()
	.GetProperty("Configuration")
	.GetValue(stateArgs.Operation);

var sources = testRequestConfiguration.GetType()
	.GetProperty("TestSources")
	.GetValue(testRequestConfiguration);

//if (testRequestConfiguration.Debug)
//	return;

foreach (string testDll in sources)
{
	...
}
```

I also saw that the Debug property has been removed...

**Comment by dozer75** [comment]
Tried 1.16.6 today with Visual Studio 16.3.10 and still not working. Getting:

```
[2019-11-28 9:31:24.778 pm Error] System.MissingMethodException: Method not found: 'Boolean Microsoft.VisualStudio.TestWindow.Controller.TestRunConfiguration.get_Debug()'.
   at PrestoCoverage.PrestoCoverageCore.OnTestExecutionStarting(Object sender, OperationStateChangedEventArgs stateArgs)
   at PrestoCoverage.PrestoCoverageContainerDiscoverer.OperationState_StateChanged(Object sender, OperationStateChangedEventArgs e) in C:\Projects\PrestoCoverage\PrestoCoverage\PrestoCoverage\PrestoCoverageContainerDiscoverer.cs:line 73
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.TestWindow.Controller.OperationData.<>c__DisplayClass44_0.<OnStateChanged>b__0()
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.CallInternalWithLogging(ILogger2 log, Action action, Boolean shouldThrow)
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by pcbl** [comment]
same issue as @dozer75 , when running the tests on Vs 2019 16.3.10.

**Comment by eduardocp** [comment]
@ppumkin had already commented above:

> I released 1.16.5 that will not cause that dumb ass exception to show any more..
> 
> **but the automagic coverage DOES NOT WORK IN 2019 YET**
> 
> You can only use the watch folder function in VS2019 for NOW.. atleast something for the time being.
> 
> Sorry for taking so long to get to it.

**Comment by dozer75** [comment]
@eduardocp Well, he stated that the "dumb ass exception" shouldn't occur anymore after 1.6.15, but it does in 1.6.16, that's why I added the message... :)

To clarify to anyone else what's this means:
If you run tests in Visual Studio 2019 it will not do auto coverage when you run the test using test explorer in visual studio (you'll get that "dumb ass exception")... 

However; if you run manually using `dotnet test /p:CollectCoverage=true /p:CoverletOutput=<Path>` where `<Path>` is the folder configured in `Tools -> Options -> PrestoCoverage -> General Settings -> Path` the coverage will be displayed.

**Comment by AXMIM** [comment]
I'm unable to install it on VS Professionnal 2019 Version 16.2.5
I get the following message.
I rebooted a few times already to no avail.
It is sad to see this extension get screwed up by VS 2019.

> 2019-12-20 11:41:35 - Microsoft VSIX Installer
> 2019-12-20 11:41:35 - -------------------------------------------
> 2019-12-20 11:41:35 - vsixinstaller.exe version:
> 2019-12-20 11:41:35 - 16.4.1057
> 2019-12-20 11:41:35 - -------------------------------------------
> 2019-12-20 11:41:35 - Command line parameters:
> 2019-12-20 11:41:35 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:16.2.29306.81,/appidname:Microsoft Visual Studio Professional 2019,/culture:en-US,/noep,C:\Users\maxiveil\AppData\Local\Temp\VSIXjfohq50j.vsix
> 2019-12-20 11:41:35 - -------------------------------------------
> 2019-12-20 11:41:35 - Microsoft VSIX Installer
> 2019-12-20 11:41:35 - -------------------------------------------
> 2019-12-20 11:41:36 - Setup instance 8d590194 requires a reboot. Reboot the machine and try again.
> 2019-12-20 11:41:36 - System.InvalidOperationException: Setup instance 8d590194 requires a reboot. Reboot the machine and try again.
>    à VSIXInstaller.SetupExtensions.GetLaunchableInstances(IQuery query)
>    à VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
>    à VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken)
>    à VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken)
>    à VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken)
>    à VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    à VSIXInstaller.App.Initialize()
>    à System.Threading.Tasks.Task`1.InnerInvoke()
>    à System.Threading.Tasks.Task.Execute()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
>

**Comment by BDomzalski** [comment]
It's nearly half-year since @iainnicol checked that the approach with DataCollectors works and a fork of Coverlet has been created. Any progress? I know from own experience that finding time might be almost impossible. I would like to see this working so maybe I could help?

**Comment by ppumkin** [comment]
Hi Bartosz. Yea I have been meaning to get back to this. I would probably spend some time tonight to look at the forks ? I didn’t see where the data collectors have been used to work ?
If you can put some links in it will
Make it faster for me to discover this and fix it maybe

________________________________

**Comment by BDomzalski** [comment]
I did a quick look around the forks but did not spot where it could be that those collectors were used. I only infer that base on the following two comments: [description of possible solution](https://github.com/ppumkin/PrestoCoverage/issues/17#issuecomment-499590687) and [approach works](https://github.com/ppumkin/PrestoCoverage/issues/17#issuecomment-502117782).

**Comment by ppumkin** [comment]
Ok. I think they thought that would work. Will have to spend some time around it.

________________________________
